### ISSUE TITLE
Fix issue with incorrect motor types

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/dodal#489]
Currently if you run the beamline system tests you will get an error like:
```
ophyd_async.core.utils.NotConnected: 
coros: NotConnected:
    gap_motor: NotConnected:
        motor_done_move: TypeError: SR04I-MO-SERVC-01:BLGAPMTR.DMOV has type int not float
        low_limit_travel: TypeError: SR04I-MO-SERVC-01:BLGAPMTR.LLM has type float not int
        high_limit_travel: TypeError: SR04I-MO-SERVC-01:BLGAPMTR.HLM has type float not int
```
This is due to https://github.com/bluesky/ophyd-async/pull/273. We should pin `dodal` to this `ophyd_async` change to avoid this breaking in prod

## Acceptance Criteria
* The system tests pass again
