### ISSUE TITLE
 ApertureScatterguard has no prefix

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/dodal#528]
When running `python tests/system_tests/test_i03_system.py`(with the devices commented out as specified in https://github.com/DiamondLightSource/dodal/issues/261) I get the following error:

```
ophyd_async.core.utils.NotConnected: 
coros: NotConnected:
    aperture: NotConnected:
        x: NotConnected:
            motor_egu: NotConnected: ca://-MO-MAPT-01:X.EGU
            velocity: NotConnected: ca://-MO-MAPT-01:X.VELO
            user_readback: NotConnected: ca://-MO-MAPT-01:X.RBV
            user_setpoint: NotConnected: ca://-MO-MAPT-01:X.VAL
            max_velocity: NotConnected: ca://-MO-MAPT-01:X.VMAX
            acceleration_time: NotConnected: ca://-MO-MAPT-01:X.ACCL
            precision: NotConnected: ca://-MO-MAPT-01:X.PREC
            deadband: NotConnected: ca://-MO-MAPT-01:X.RDBD
            motor_done_move: NotConnected: ca://-MO-MAPT-01:X.DMOV
            low_limit_travel: NotConnected: ca://-MO-MAPT-01:X.LLM
            high_limit_travel: NotConnected: ca://-MO-MAPT-01:X.HLM
            motor_stop: NotConnected: ca://-MO-MAPT-01:X.STOP
        y: NotConnected:
            motor_egu: NotConnected: ca://-MO-MAPT-01:Y.EGU
            velocity: NotConnected: ca://-MO-MAPT-01:Y.VELO
            user_readback: NotConnected: ca://-MO-MAPT-01:Y.RBV
            user_setpoint: NotConnected: ca://-MO-MAPT-01:Y.VAL
            max_velocity: NotConnected: ca://-MO-MAPT-01:Y.VMAX
            acceleration_time: NotConnected: ca://-MO-MAPT-01:Y.ACCL
            precision: NotConnected: ca://-MO-MAPT-01:Y.PREC
            deadband: NotConnected: ca://-MO-MAPT-01:Y.RDBD
            motor_done_move: NotConnected: ca://-MO-MAPT-01:Y.DMOV
            low_limit_travel: NotConnected: ca://-MO-MAPT-01:Y.LLM
            high_limit_travel: NotConnected: ca://-MO-MAPT-01:Y.HLM
            motor_stop: NotConnected: ca://-MO-MAPT-01:Y.STOP
        z: NotConnected:
            motor_egu: NotConnected: ca://-MO-MAPT-01:Z.EGU
            velocity: NotConnected: ca://-MO-MAPT-01:Z.VELO
            user_readback: NotConnected: ca://-MO-MAPT-01:Z.RBV
            user_setpoint: NotConnected: ca://-MO-MAPT-01:Z.VAL
            max_velocity: NotConnected: ca://-MO-MAPT-01:Z.VMAX
            acceleration_time: NotConnected: ca://-MO-MAPT-01:Z.ACCL
            precision: NotConnected: ca://-MO-MAPT-01:Z.PREC
            deadband: NotConnected: ca://-MO-MAPT-01:Z.RDBD
            motor_done_move: NotConnected: ca://-MO-MAPT-01:Z.DMOV
            low_limit_travel: NotConnected: ca://-MO-MAPT-01:Z.LLM
            high_limit_travel: NotConnected: ca://-MO-MAPT-01:Z.HLM
            motor_stop: NotConnected: ca://-MO-MAPT-01:Z.STOP
        small: NotConnected: ca://-MO-MAPT-01:Y:SMALL_CALC
        medium: NotConnected: ca://-MO-MAPT-01:Y:MEDIUM_CALC
        large: NotConnected: ca://-MO-MAPT-01:Y:LARGE_CALC
    scatterguard: NotConnected:
        x: NotConnected:
            motor_egu: NotConnected: ca://-MO-SCAT-01:X.EGU
            velocity: NotConnected: ca://-MO-SCAT-01:X.VELO
            user_readback: NotConnected: ca://-MO-SCAT-01:X.RBV
            user_setpoint: NotConnected: ca://-MO-SCAT-01:X.VAL
            max_velocity: NotConnected: ca://-MO-SCAT-01:X.VMAX
            acceleration_time: NotConnected: ca://-MO-SCAT-01:X.ACCL
            precision: NotConnected: ca://-MO-SCAT-01:X.PREC
            deadband: NotConnected: ca://-MO-SCAT-01:X.RDBD
            motor_done_move: NotConnected: ca://-MO-SCAT-01:X.DMOV
            low_limit_travel: NotConnected: ca://-MO-SCAT-01:X.LLM
            high_limit_travel: NotConnected: ca://-MO-SCAT-01:X.HLM
            motor_stop: NotConnected: ca://-MO-SCAT-01:X.STOP
        y: NotConnected:
            motor_egu: NotConnected: ca://-MO-SCAT-01:Y.EGU
            velocity: NotConnected: ca://-MO-SCAT-01:Y.VELO
            user_readback: NotConnected: ca://-MO-SCAT-01:Y.RBV
            user_setpoint: NotConnected: ca://-MO-SCAT-01:Y.VAL
            max_velocity: NotConnected: ca://-MO-SCAT-01:Y.VMAX
            acceleration_time: NotConnected: ca://-MO-SCAT-01:Y.ACCL
            precision: NotConnected: ca://-MO-SCAT-01:Y.PREC
            deadband: NotConnected: ca://-MO-SCAT-01:Y.RDBD
            motor_done_move: NotConnected: ca://-MO-SCAT-01:Y.DMOV
            low_limit_travel: NotConnected: ca://-MO-SCAT-01:Y.LLM
            high_limit_travel: NotConnected: ca://-MO-SCAT-01:Y.HLM
            motor_stop: NotConnected: ca://-MO-SCAT-01:Y.STOP
```

## Acceptance Criteria
* The system tests for i03 pass (with exceptions expected in https://github.com/DiamondLightSource/dodal/issues/261)
